### ISSUE TITLE
tm1py connect to power bi with config file

### ISSUE THREAD

**Issue by Adamgyorgy74** [cubewise-code/tm1py#817] opened 2022-10-19 08:54 UTC
Basically i can connect to power bi with tm1py.
I use this code:

```
from TM1py import TM1Service
from TM1py.Utils import Utils

creds = {
    "address":"---", 
    "port":---, 
    "port2":---,
    "user":"----", 
    "namespace":"---",
    "password":"-------",
    "ssl":False
}
with TM1Service(address=creds['address'],port=creds['port2'],user=creds['user'],namespace=creds['namespace'],password=creds['password'],ssl=creds['ssl']) as tm1:
    mdx="""
-- 
    """   
    df = tm1.power_bi.execute_mdx(mdx) 
df
```
Run well have no prolem.

But
I tried connect with config file.
I folloved the descriptions with the recommended code  but not working.
My message is:
key error: 'tm1srv01'

**Comment by MariusWirtz** [comment] 2022-10-19 08:56
Try to use absolute path to config file

**Comment by Adamgyorgy74** [comment] 2022-10-19 09:07
Here is the code what i try to use

import configparser
from TM1py import TM1Service

config = configparser.ConfigParser()
config.read('C:\\TM1py\\power-bi\\config.ini')

with TM1Service(**config["tm1srv01"]) as tm1: 
  mdx  =  """ 
  --here is the mdx code
          """
df = tm1.power_bi.execute_mdx(mdx) 

df

**Comment by MariusWirtz** [comment] 2022-10-19 09:11
please post the structure of the config.ini as well.

**Comment by Adamgyorgy74** [comment] 2022-10-19 09:12
[tm1srv01]
address=xxxxxx
port=xxxx
namespace=xxxx
user=username
password=password
ssl=False

**Comment by Adamgyorgy74** [comment] 2022-10-19 09:23
My tm1py version is: 1.10.0
And if i try to update to 1.5 
this is the result :Requirement already satisfied

**Comment by MariusWirtz** [comment] 2022-10-19 09:24
The problem is that the config.ini file is not read. Try to use `/` for the path

**Comment by Adamgyorgy74** [comment] 2022-10-19 09:39
Better! Something changed:

<pi>TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '' - Status Code: 401 - Reason: 'Unauthorized' - Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'Set-Cookie': 'TM1SessionId=HpzIrykjpvpW6M-mJRhxRA; Path=/api/; HttpOnly', 'WWW-Authenticate': 'CAMPassport http://......................'}
</pi>”

**Comment by MariusWirtz** [comment] 2022-10-19 10:19
Unauthorized can mean two things.
- you are providing the wrong login information (e.g. user, password, namespace)
- your user doesn't have permission to do the operation

given that you were able to authenticate before you only need to make sure the config.ini contains the same arguments as you were providing before to the TM1Serice I will close this issue as it's not a TM1py issue.

**Closed by MariusWirtz** 2022-10-19 10:19 UTC
Labels: question

**Comment by Adamgyorgy74** [comment] 2022-10-19 11:44
Thanks for your help.
Have a nice day
