### ISSUE TITLE
How to get elements from a subset directly from mdx ?

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#159] opened 2019-07-18 19:45 UTC
Hi, 

I've been using mdx to extract values from cubes, however it's not very clear to me the best way to extract elements from a dimension's subset.

The only way I found is:

First:

Create a subset:

    def build_subset(tm1, dimension_name, Funcionários):
        x = "{FILTER({TM1FILTERBYLEVEL( {TM1SUBSETALL( [Itens Headcount] )}, 0)},[PLA_PlanoAcao].([Métricas Plano].[Responsável]) = 10)}"
        subset = Subset('teste', dimension_name=dimension_name, hierarchy_name=dimension_name, expression=x)
        if not tm1.dimensions.hierarchies.subsets.exists('teste', dimension_name, dimension_name, private=False):
            tm1.dimensions.hierarchies.subsets.create(subset, private=False)
        else:
            tm1.dimensions.hierarchies.subsets.update(subset, private=False)
Then apply:
```
    subset_cost_center = tm1.dimensions.subsets.get(subset_name=''teste'',
                                                    dimension_name='Status',
                                                    hierarchy_name=dimension_name,
                                                    private=False)
```

Is there a good way to do this directly from mdx ?

Something like:

```
 x = "{TM1FILTERBYLEVEL( {TM1SUBSETALL( [Itens Headcount] )}, 0}

mdx_result = tm1.cubes.cells.execute_mdx(x)
```

**Comment by MariusWirtz** [comment] 2019-07-18 19:56
You can use the `execute_mdx` method from the `DimensionService`:
```
with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PASSWORD, ssl=SSL, decode_b64=DECODE_B64) as tm1:
    elements = tm1.dimensions.execute_mdx(dimension_name="Date", mdx="{Tm1SubsetAll([Date])}")
```

**Comment by kaleming** [comment] 2019-07-18 19:59
Thank you very much Marius

**Comment by FHoile** [comment] 2024-01-24 05:48
I've come this page very late obviously.  Seems the solution has now been deprecated, because when I try this I get the following response from Python:

**<ipython-input-14-d23aeb6c978a>:16: DeprecationWarning: execute_mdx() will be deprecated; use ElementService execute_set_mdx.
  elements = tm1.dimensions.execute_mdx(dimension_name="myDimensionNameWasHere", mdx=sMdxDim)**

The first run it never executed.  On a second run it did execute and return a list of elements.  But given the deprecation warning, I guess I better look for different syntax.

**Comment by FHoile** [comment] 2024-01-24 06:17
So searching around, I'm using this syntax instead (and I wanted it returned as a dataFrame anyway, so this is good) and not getting the deprecation warning with this one:

**elementsDf = tm1.elements.get_elements_dataframe(dimension_name="myDimName", hierarchy_name="myDimName", elements=sMdxDim)**

Strangely, if I try to utilise the use_blob parameter specified in the documentation... ie: if I instead run this:
**elementsDf = tm1.elements.get_elements_dataframe(dimension_name="myDimName", hierarchy_name="myDimName", elements=sMdxDim, use_blob=True)**

...then it always returns an error.  So I'm just going to leave out the use_blob argument for now I guess.

**Comment by MariusWirtz** [comment] 2024-01-24 07:33
@FHoile 
Please post the error you receive when using the `use_blob` mode.

Is the error still raised when you upgrade TM1py to the current master branch on GitHub?

```
Pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/master.zip --upgrade
```

**Comment by FHoile** [comment] 2024-01-25 01:19
Hi @MariusWirtz ,

I'm not overly worried about the use_blob=True error at the moment, as the function still works if I omit that argument.  

Side note: I do use that argument in other functions successfully.   An example is this one which works fine:  
`tm1.cubes.cells.write_dataframe(cube_name=myCube, data=myDataFrame, increment=False, use_blob=True)`

I'm sure it is just an old version issue.  I'm overdue to upgrade TM1 itself.  Haven't been in a rush to upgrade TM1Py itself as haven't wanted to risk any backwards-compatibility issues in scripts that are currently working daily in production.

On the dev box, where I'm writing all this, the versions I'm running on are:
- TM1 = 11.6.00004.2
- TM1Py = 1.11.2

If I get a spare moment (which won't be for a while), I might try creating a virtual python environment and upgrading TM1Py there as you suggested, and retesting.  I definitely know upgrades are overdue!

**In terms of the current error message though, it is shown below:**
d:\program files\python38\lib\site-packages\TM1py\Services\TM1Service.py in __init__(self, **kwargs)
     14 
     15     def __init__(self, **kwargs):
---> 16         self._tm1_rest = RestService(**kwargs)
     17         self.annotations = AnnotationService(self._tm1_rest)
     18         self.cells = CellService(self._tm1_rest)

d:\program files\python38\lib\site-packages\TM1py\Services\RestService.py in __init__(self, **kwargs)
    224         self._s = requests.session()
    225 
--> 226         self.connect()
    227 
    228         if not self._version:

d:\program files\python38\lib\site-packages\TM1py\Services\RestService.py in connect(self)
    244             self._s.cookies.set("TM1SessionId", self._kwargs["session_id"])
    245         else:
--> 246             self._start_session(
    247                 user=self._kwargs.get("user", None),
    248                 password=self._kwargs.get("password", None),

d:\program files\python38\lib\site-packages\TM1py\Services\RestService.py in _start_session(self, user, password, decode_b64, namespace, gateway, cam_passport, integrated_login, integrated_login_domain, integrated_login_service, integrated_login_host, integrated_login_delegate, impersonate)
    423 
    424             if response is None:
--> 425                 raise ValueError(f"No response returned from URL: '{self._base_url + url}'. "
    426                                  f"Please double check your address and port number in the URL.")
    427 

ValueError: No response returned from URL: 'https://dca-tmdev01.ipo.local:8554/api/v1/Configuration/ProductVersion/$value'. Please double check your address and port number in the URL.

**Comment by FHoile** [comment] 2024-01-25 04:03
Although actually... weirdly, the function omitting the **use_blob** has just started failing now too.  Code has not changed so it's quite strange.  Not sure if this post here is the correct spot to talk about it though.  I'll need to do some more tests first.  It was working yesterday though.

**Comment by MariusWirtz** [comment] 2024-01-25 10:31
Regarding

```
RuntimeError: Failed writing to blob with TI. Status: 'Aborted' log: 'TM1ProcessError_20240125035018_14913536_.log'
Error Message In TM1:
Error: Prolog procedure line (0): Unable to open data source "}ElementAttributes_myDimensionNameHere".
```

Is this a scenario where the `}ElementAttributes_` cube doesn't exist for a dimension?

Regarding 

> the function omitting use_blob also fails, if the MDX is valid but returns no results.

I will look into this and try to reproduce

**Comment by MariusWirtz** [comment] 2024-01-25 17:48
This should resolve the issues related to `use_blob` https://github.com/cubewise-code/tm1py/pull/1040

**Comment by FHoile** [comment] 2024-01-30 08:18
> Regarding
> 
> ```
> RuntimeError: Failed writing to blob with TI. Status: 'Aborted' log: 'TM1ProcessError_20240125035018_14913536_.log'
> Error Message In TM1:
> Error: Prolog procedure line (0): Unable to open data source "}ElementAttributes_myDimensionNameHere".
> ```
> 
> Is this a scenario where the `}ElementAttributes_` cube doesn't exist for a dimension?
> 
> Regarding
> 
> > the function omitting use_blob also fails, if the MDX is valid but returns no results.
> 
> I will look into this and try to reproduce

Hi Marius.  
Correct, there is no attributes cube for that dimension.  (And no scope to add one as the dimension is massive).

Thanks for looking into this and resolving.  I have all my code working nicely without use_blob = true and with a try/except to deal with empty result sets.  But if I get a chance I might look to update pip update TM1Py to the latest version and retest without my work-arounds.

**Closed** 2024-01-30 09:06 UTC
Labels: question
