### ISSUE TITLE
MDX DIMENSION PROPERTIES not working in execute_mdx_dataframe

### ISSUE THREAD

**Issue by macsir** [cubewise-code/tm1py#524] opened 2021-04-09 04:22 UTC
**Describe the bug**
MDX DIMENSION PROPERTIES not working in execute_mdx_dataframe using include_attributes=True parameter

**To Reproduce**
Add this bit to " DIMENSION PROPERTIES [Product].[Product].[Full Desc] ON 1 FROM [cube]" a working mdx and with include_attributes parameter used in execute_mdx_dataframe

**Expected behavior**
I expect to give me a new product Full Desc column in the result?

**Version**
TM1py 1.6
TM1 Server Version: 11.8

**Additional context**
Errors:
Traceback (most recent call last):
  File "c:\Users\xyz\Documents\test.py", line 89, in <module>
    df = tm1.cells.execute_mdx_dataframe(mdx, include_attributes=True)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Services\CellService.py", line 1013, in execute_mdx_dataframe
    return self.extract_cellset_dataframe(cellset_id, top=top, skip=skip, skip_zeros=skip_zeros,
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Services\CellService.py", line 1715, in extract_cellset_dataframe
    return pd.read_csv(memory_file, sep='~', **kwargs)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 85 fields in line 10, saw 86

**Comment by MariusWirtz** [comment] 2021-04-09 08:58
Is this perhaps a duplicate of https://github.com/cubewise-code/tm1py/issues/507 ?

Are you explicitly stating with properties you want to retrieve, like in this sample?

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, user="admin", password="apple", ssl=True) as tm1:
    mdx = """
    SELECT
    {Tm1SubsetAll([d1])} PROPERTIES [d1].[Attribute Something] ON 0,
    {Tm1SubsetAll([d2])} PROPERTIES [d2].[Number] ON 1
    FROM [c1]
    """

    data = tm1.cells.execute_mdx_dataframe(mdx, include_attributes=True)

    print(data)
```

**Comment by macsir** [comment] 2021-04-09 09:15
Thanks, @MariusWirtz for the prompt reply. Does that mean I need to specify PROPERTIES on columns (PROPERTIES MEMBER_NAME by default) as well to get it work?

**Comment by MariusWirtz** [comment] 2021-04-09 10:28
Yes. You need to specify properties explicitly.

@beckyconning is currently working on a fix, but for the moment the properties need to be specified explicitly.

**Comment by macsir** [comment] 2021-04-09 10:42
I tried but still same errors. If I have multiple dimensions on rows, do I have to include property for each dimension for it? Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MariusWirtz** [comment] 2021-04-09 10:44
please post your MDX here

**Comment by macsir** [comment] 2021-04-09 10:58
Thanks for the reply. Have to leave now and will post something later.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by macsir** [comment] 2021-04-10 10:37
Hi, @MariusWirtz 
I had another look today and realized I didn't put MEMBER_NAME beside [Product].[Product].[Full Desc] previously and only added it to 0 axis. Now it is working fine! Thank you. :)

SELECT{[TESTMEASURE].[TESTMEASURE].[AMOUNT]} DIMENSION PROPERTIES MEMBER_NAME ON 0, NON EMPTY {[VERSION].[VERSION].[PLAN]} * {[PRODUCT].[PRODUCT].[0753],[PRODUCT].[PRODUCT].[0801],[PRODUCT].[PRODUCT].[0802],[PRODUCT].[PRODUCT].[0803]} DIMENSION PROPERTIES MEMBER_NAME, [Product].[Product].[Full Desc] ON 1 FROM [ZTMPTEST2]

**Closed** 2021-04-12 06:08 UTC
Labels: bug
