### ISSUE TITLE
Cannot connect to TM1 with Intgreated mode=5 with SSO

### ISSUE THREAD

**Issue by aagrawal12** [cubewise-code/tm1py#509] opened 2021-03-10 17:16 UTC
I am trying to connect to TM1. It works when i have integrated mode=1.

But when I am trying with mode 5it says 
"   line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
line 185, in __init__
    self._start_session(
", line 335, in _start_session
    token = self._build_authorization_token(
, line 447, in _build_authorization_token
    return RestService._build_authorization_token_cam(user, password, namespace, gateway, verify)
, line 468, in _build_authorization_token_cam
    raise RuntimeError(
RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

**Comment by MariusWirtz** [comment] 2021-03-10 18:48
Are you trying to use TM1py with CAM SSO? 

If yes, does SSO work in your environment for other TM1 clients like TM1web or Architect/Perspectives?

**Comment by aagrawal12** [comment] 2021-03-10 19:09
Thanks for responding. Yes SSO works in TM1 web and Architect/Perspective

**Comment by aagrawal12** [comment] 2021-03-10 21:03
from TM1py.Services import TM1Service

tm1 = TM1Service(address='AdminHost', port=12354, namespace='OKTA', gateway=ClientCAMURI', ssl='False')

server_name = tm1.server.get_server_name()


print("Connection to TM1 established!! your Servername is: {}".format(server_name))

**Comment by harveyca307** [comment] 2021-03-10 21:30
Look at: https://code.cubewise.com/tm1py-help-content/category/Configuration  

It gives examples for how to connect.  Your TM1Service call does not look right

**Comment by MariusWirtz** [comment] 2021-03-11 12:58
@aagrawal12 be careful, the namespace is case sensitive.

**Comment by aagrawal12** [comment] 2021-03-11 16:46
@MariusWirtz Yes i am aware and have inexact format how it is defined. Still no luck

**Comment by MariusWirtz** [comment] 2021-03-15 12:20
@aagrawal12,
We have an open discussion about (potential) issues with CAM SSO.

Can you please try to follow the steps discussed here: https://github.com/cubewise-code/tm1py/issues/399#issuecomment-729668567

The MR has been merged in the meantime, so you just need to upgrade to the current master on GitHub
`pip install https://github.com/brandond/requests-negotiate-sspi/archive/master.zip --upgrade`

**Comment by aagrawal12** [comment] 2021-03-17 17:52
Still no luck..still getting error RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

**Comment by MariusWirtz** [comment] 2021-03-18 11:11
Hi @aagrawal12,

could you please try if the below workaround proposed by @ChristianThieme works for you?
https://github.com/cubewise-code/tm1py/issues/124#issuecomment-491852908

**Comment by aagrawal12** [comment] 2021-03-19 01:17
Hi @MariusWirtz i tried the workaround but i am still getting same error.

Thanks and appreciate you replying back. I will keep exploring and look forward any other workaround you have to offer

**Comment by rkvinoth** [comment] 2021-04-06 13:07
@aagrawal12 
1. Does it automatically log you in when you look up the **CLIENTCAMURI** in your browser? 
2. Should **SSL** be `False` in your case?
3. What all cookies do you get when you run the following code?

```PYTHON
from requests_negotiate_sspi import HttpNegotiateAuth
import requests


gateway="CLIENTCAMURI"
response = requests.get(gateway, auth=HttpNegotiateAuth(), verify=False, params={"CAMNamespace": "NAMESPACE"})

print([cookie.name for cookie in response.cookies])

```

**Comment by aagrawal12** [comment] 2021-04-06 17:18
@rkvinoth 

My answers below:

Does it automatically log you in when you look up the CLIENTCAMURI in your browser?
    Yes
Should SSL be False in your case?
  Yes SSL is false. I checked in Configurations and we dont have it enabled
What all cookies do you get when you run the following code?
   This are cookies i got  ['XSRF-TOKEN', 'CRN']

Thanks for looking into it this and any help would be appreciated. I am out of ideas and cant get it to resolve

**Comment by rkvinoth** [comment] 2021-04-06 17:26
This is what I get:
`['XSRF-TOKEN', 'cam_passport', 'usersessionid', 'CRN', 'cc_session', 'cea-ssa', 'userCapabilities', 'userCapabilitiesEx']`

You should talk to your Admin team and setup Cognos Analytics properly (not an expert here). If they don't know about it or if you don't have an Admin team, setup some time with IBM.

**Comment by meyersrl** [comment] 2021-08-10 18:11
> This is what I get:
> `['XSRF-TOKEN', 'cam_passport', 'usersessionid', 'CRN', 'cc_session', 'cea-ssa', 'userCapabilities', 'userCapabilitiesEx']`
> 
> You should talk to your Admin team and setup Cognos Analytics properly (not an expert here). If they don't know about it or if you don't have an Admin team, setup some time with IBM.


While I eventually get this response when hitting the CA portal....... during my testing the first response only includes the XRF-Token.  There are many other calls back to the Cognos dispatcher before I get a response that includes all of the cookies including the necessary cam_passport cookie.

It seems like due to having SSO enabled the first call is rejected and the response comes back with 3 authentication headers.  

`WWW-Authenticate Header is present: Negotiate

WWW-Authenticate Header is present: NTLM

WWW-Authenticate Header is present: Basic realm="CA Server"`

A new call is generated with the first header "Negotiate" and a new response is generated with the correct cookies.

As for TM1Py

The first request shows it doesn't contain a WWW-Authenticate header.  So it then receives a response from CA with the 3 WWW-Authenticate headers that are possible.

Another request is made with the WWW-Authenticate: Negotiate header which shows a 200 response.  However it does not contain the cam_passport and therefore TM1Py is showing no cam_passport cookie error.

Im not sure why there seems to be another call and response when hitting the CA Portal which does contain the cam_passport vs TM1Py which seems to stop after the response that only contains the XSRF-Token.

**Comment by meyersrl** [comment] 2021-08-12 18:54
Ryan Clapp has a post on the IBM Community site that I think represents the problem for TM1Py trying to use SSO with CAM for login.

[](https://community.ibm.com/community/user/businessanalytics/communities/community-home/digestviewer/viewthread?GroupId=3061&MessageKey=83050261-51fe-459e-b771-7884ede80804&CommunityKey=6b10df83-0b3c-4f92-8b1f-1fd80d0e7e58&tab=digestviewer)

**Comment by meyersrl** [comment] 2021-10-06 18:15
Update - Using PyCharm as the IDE the integrated login seems to work.  I was using Jupyter previously and couldn't get it to work.

**Comment by meyersrl** [comment] 2021-10-08 22:49
I have been working a bit more at this and for some reason our PROD environment/network will allow for CAM Mode 5 Authentication with TM1Py.  However our DEV environment/network won't.  Whats strange is that all components are the same version, both environments use the same connection to our PROD Active Directory through the same version of Cognos Analytics.  On top of that SSO seems to work just fine in our DEV environment as we don't get prompted for login.  At this point it looks more like a network or settings issue on our side vs TM1py

**Comment by meyersrl** [comment] 2021-10-21 20:07
Im noticing a slight difference in Fiddler between logging in to TM1Web in our DEV vs PROD environment.  In DEV there is an extra call with the negotiate authentication header.  In PROD it seems as if it attempts NTLM first and doesn't use negotiate. I checked IIS and negotiate is disabled for both.  Ill keep looking to see if the gateway's somehow are different.

**Comment by MariusWirtz** [comment] 2022-09-19 16:26
@meyersrl 
can you confirm that the issue persists after you made the following change to the Cognos configuration:
-  Security -> Authentication -> Cognos -> Allow Anonymous Access? to **True**.
-  and verified that you are using the right CAM namespace ID

**Closed by MariusWirtz** 2022-09-19 16:26 UTC
Labels: bug

**Comment by RobbyMeyers** [comment] 2023-07-11 21:05
Hi Marius, I can confirm that setting Allow Anonymous Access to True and restarting the dispatcher worked.  Is there any fix for this?  Unfortunately setting Anonymous to True in some cases allows users to login to TM1 as Anonymous which is not what we want.

**Comment by RobbyMeyers** [comment] 2023-09-20 20:06
Is there any way to make this work without having to allow anonymous on the gateway?
