### ISSUE TITLE
execute_mdx_dataframe() results in "ERROR: could not convert string to float: 'xxx'" when returned value is a string

### ISSUE THREAD

**Issue by headmann** [cubewise-code/tm1py#579] opened 2021-07-27 15:07 UTC
**Describe the bug**
execute_mdx_dataframe() results in "ERROR: could not convert string to float: 'xxx'" when returned value is a string

However, when using execute_mdx() and then converting result to the dataframe using Utils.build_pandas_dataframe_from_cellset() it works perfectly.

**To Reproduce**
Error:
====
mdx = """NON EMPTY {TM1SORT({TM1FILTERBYLEVEL({TM1SUBSETALL([}CLIENTS].[}CLIENTS])},0)},ASC)} * {TM1SORT({TM1FILTERBYLEVEL({TM1SUBSETALL([}GROUPS].[}GROUPS])},0)},ASC)} ON 0
FROM [}CLIENTGROUPS]"""

try:
    with TM1Service(**config[PA_SERVER]) as tm1:
        df = tm1.cubes.cells.execute_mdx_dataframe(mdx)
        print(df)

except Exception as e:
    print("\nERROR:")
    print("\t" + str(e))
===

Works well:
====
mdx = """NON EMPTY {TM1SORT({TM1FILTERBYLEVEL({TM1SUBSETALL([}CLIENTS].[}CLIENTS])},0)},ASC)} * {TM1SORT({TM1FILTERBYLEVEL({TM1SUBSETALL([}GROUPS].[}GROUPS])},0)},ASC)} ON 0
FROM [}CLIENTGROUPS]"""

try:
    with TM1Service(**config[PA_SERVER]) as tm1:
        content = tm1.cubes.cells.execute_mdx(mdx=mdx)
        df = Utils.build_pandas_dataframe_from_cellset(content)
        print(df)

except Exception as e:
    print("\nERROR:")
    print("\t" + str(e))

**Expected behavior**
Function should support string values. 

**Version**
TM1py 1.6.2
TM1 Server Version: 11.8.00300.34 (IBM Cloud)

**Comment by MariusWirtz** [comment] 2021-07-27 15:10
duplicate of #248 

please re-open if I got this wrong

**Closed by MariusWirtz** 2021-07-27 15:10 UTC
Labels: bug
