### ISSUE TITLE
Pandas ParserError and shifted dataframe columns when executing MDX dataframe with attributes

### ISSUE THREAD

**Issue by tobiaskapser** [cubewise-code/tm1py#718] opened 2022-05-13 10:13 UTC
**Describe the bug**
When using the function `execute_mdx_dataframe()` from the Cells-Service with the parameter `include_attributes=True` pandas throws an `pandas.errors.ParserError` is some cases. In other cases a dataframe with shifted columns is returned.

**To Reproduce**
For the GO_Scorecards-Cube from the 'GO_Scorecards' sample system I define the following MDX:
```
SELECT NON EMPTY
{TM1SUBSETALL( [country] )}
ON ROWS,
{TM1SUBSETALL( [Time] )}
ON COLUMNS
FROM [GO_Scorecards]
WHERE ([Metric Indicators].[Actual], [gometric].[Gross profit])
```
and execute the view with the following function call:
```
tm1.cubes.cells.execute_mdx_dataframe(MDX, include_attributes=True)
```

In this case pandas throws the error 
```
pandas.errors.ParserError: Error tokenizing data. C error: Expected 62 fields in line 3, saw 63
```

Interestingly if I use the `skip_consolidated_cells=True` parameter in the function call a dataframe is return without an error. But in this case the columns in the dataframe are shifted:

```
         country      Caption Caption Kazakh Caption Slovenian  ... Caption_Default.1 }RollUpName            New Years Value
0         Canada       Canada         Канада            Kanada  ...           2013-01    Jan 2017   -9106.356169672275   NaN
1         Canada       Canada         Канада            Kanada  ...           2013-02    Feb 2017  -13524.638859299748   NaN
2         Canada       Canada         Канада            Kanada  ...           2013-03    Mar 2017   -15080.53051216054   NaN
3         Canada       Canada         Канада            Kanada  ...           2013-04    Apr 2017  -24833.612386099565   NaN
4         Canada       Canada         Канада            Kanada  ...           2013-05    May 2017  -24345.803206734254   NaN
..           ...          ...            ...               ...  ...               ...         ...                  ...   ...
382  Switzerland  Switzerland      Швейцария             Švica  ...           2010-08    Aug 2014   -53324.85436833359   NaN
383  Switzerland  Switzerland      Швейцария             Švica  ...           2010-09    Sep 2014   -51364.78948842073   NaN
384  Switzerland  Switzerland      Швейцария             Švica  ...           2010-10    Oct 2014   -54099.27776716403   NaN
385  Switzerland  Switzerland      Швейцария             Švica  ...           2010-11    Nov 2014   -62922.97260378283   NaN
386  Switzerland  Switzerland      Швейцария             Švica  ...           2010-12    Dec 2014   -52975.76976707139   NaN
```

The column "Value" is NaN, the column "New Years" contains the actual values and so on.

At the moment I do not completely understand in which case this shift of the columns appears. It seems like there are issues if some attributes are not completely populated with values.
In my example case the shift appears in the column "firstperiod" in the dataframe, which should contain no value in the first row.

**Expected behavior**
Some MDX-statements are working fine. If I restrict the time dimension in my example case like this
```
SELECT NON EMPTY
{TM1SUBSETALL([country])}
ON ROWS,
{[Time].[2013]}
ON COLUMNS
FROM [GO_Scorecards]
WHERE ([Metric Indicators].[Actual], [gometric].[Gross profit])
```
the correct dataframe is returned.

**Version**
TM1py 1.9.1
TM1 Server Version: 11.8.00401.1

**Additional context**
None

**Comment by tobiaskapser** [comment] 2022-05-13 10:16
Seems like it could be related to #507

**Comment by MariusWirtz** [comment] 2022-05-13 10:16
Possible duplicate of https://github.com/cubewise-code/tm1py/issues/507

Can you try to specify the attribute you want explicitly in the MDX and see if it resolved the issue?

**Comment by MariusWirtz** [comment] 2022-05-13 10:17
@tobiaskapser feel free to solve #507. It's been on my list for a while but I haven't gotten to it yet.

**Comment by tobiaskapser** [comment] 2022-05-13 11:01
> @tobiaskapser feel free to solve #507. It's been on my list for a while but I haven't gotten to it yet.

Yes, I'll look into it if I find some time in the next few days 😄

**Comment by MariusWirtz** [comment] 2022-06-12 17:25
resolved with #746

**Closed by MariusWirtz** 2022-06-12 17:25 UTC
Labels: bug
