### ISSUE TITLE
execute_mdx_dataframe can't extract string value?

### ISSUE THREAD

**Issue by macsir** [cubewise-code/tm1py#510] opened 2021-03-12 03:31 UTC
Hi, @MariusWirtz 
I have constructed a valid mdx using mdxpy but failed to retrieve value via execute_mdx_dataframe. ""test22" is a string value.
It gives me the following errors:
raceback (most recent call last):
  File "pandas\_libs\parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\testMDXClear.py", line 43, in <module>
    df = tm1.cubes.cells.execute_mdx_dataframe(mdx)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Services\CellService.py", line 1012, in execute_mdx_dataframe
    return self.extract_cellset_dataframe(cellset_id, top=top, skip=skip, skip_zeros=skip_zeros,
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\TM1py\Services\CellService.py", line 1703, in extract_cellset_dataframe
    return pd.read_csv(memory_file, sep='~', **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas\_libs\parsers.pyx", line 1147, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'test22'

**Comment by MariusWirtz** [comment] 2021-03-12 08:15
duplicate of https://github.com/cubewise-code/tm1py/issues/248

**Closed by MariusWirtz** 2021-03-12 08:15 UTC

**Comment by macsir** [comment] 2021-03-12 11:24
Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
